# -*- coding: utf-8 -*-
"""Python_mock_test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JX3QJzEPg5SAswwRskTBnfbl62d1uiJr

1
Write a function that takes a list of numbers as input and returns a new list containing only the even numbers from the input list. Use list comprehension to solve this problem.
"""

def com_list(a):
  a1=[a for a in a if a%2!=0]
  return a1


a=[2,4,5,6,2,5,12,5,24]

com_list(a)

"""Implement a decorator function called ‘timer’ that measures the execution time of a function. The ‘timer’ decorator should print the time taken by the decorated function to execute. Use the ‘time’ module in Python to calculate the execution time."""

import time

def timer(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        execution_time = end_time - start_time
        print(f"Execution time: {execution_time} seconds")
        return result
    return wrapper

@timer
def my_function():
    # Code to be timed
    time.sleep(2)

my_function()

"""3. Write a function called ‘calculate_mean’ that takes a list of numbers as input and returns the mean (average) of the numbers. The function should calculate the mean using the sum of the numbers divided by the total count."""

def calculate_mean(numbers):
    total = sum(numbers)
    count = len(numbers)
    mean = total / count
    return mean

data = [10, 15, 20, 25, 30]
mean_value = calculate_mean(data)
print("Mean:", mean_value)

"""4.Write a function called ‘perform_hypothesis_test’ that takes two lists of numbers as input, representing two samples. The function should perform a two-sample t-test and return the p-value. Use the ‘scipy.stats’ module in Python to calculate the t-test and p-value."""

from scipy import stats

def perform_hypothesis_test(sample1, sample2):
    t_statistic, p_value = stats.ttest_ind(sample1, sample2)
    return p_value

sample1 = [7, 8, 15, 30, 50]
sample2 = [10, 2, 28, 10, 50]
p_value = perform_hypothesis_test(sample1, sample2)
print("P-value:", p_value)

